name: Build unluac (Windows)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-native-image:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add GraalVM to PATH
        run: |
          echo "${{ env.GRAALVM_HOME }}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: pwsh

      - name: Install Native Image
        run: |
          & "${{ env.GRAALVM_HOME }}\bin\gu" install native-image
        shell: pwsh

      - name: Compile Java Source Files
        run: |
          mkdir build
          javac -deprecation -Werror -d build -sourcepath src  src/unluac/*.java

      - name: Create JAR File
        run: |
          mkdir bin
          jar -cfm bin/unluac.jar src/unluac/Manifest.mf -C build .

      - name: Create Native Binary
        run: |
          native-image -jar bin/unluac.jar -H:Name=unluac -H:Class=unluac.Main

      - name: Upload Native Binary
        uses: actions/upload-artifact@v3
        with:
          name: unluac
          path: ./unluac.exe
